### ISSUE TITLE
Removal of pinned packages

### ISSUE THREAD

**Issue by zitterbewegung** [revalo/tree-diffusion#4]
I have trouble building this on ubuntu 22.04

pip install -r requirements.txt fails on a virtualenv for 3.11 on 3.10 it builds but I had to remove pinned packages.

`absl_py==1.4.0

datrie==0.8.2

dm_tree==0.1.8

lark==1.1.9

lz4==4.3.3

numpy

pathos

rich==13.7.1

scipy==1.13.0

skia_python==87.5

timm

torch

tqdm==4.66.1

wandb==0.16.4

iceberg-dsl @ git+https://github.com/revalo/iceberg.git@db446c1ed`

**Comment by RobertasJ** [comment]
thanks for saving me a bunch of time
